version: "3.3"
services:
  worker:
    build: .
    environment:
      DATABASE_URI: $DATABASE_URI
      SESSION: $SESSION
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      
